Post  http://testing.stimiksepnop.ac.id/api/Persyaratan HTTP/1.1
content-type: application/json
Authorization: 

{
    "nama":"KTP"
}

###

PUT  http://testing.stimiksepnop.ac.id/api/Persyaratan/4 HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjgiLCJVc2VybmFtZSI6IkNhbmRyYSIsIkVtYWlsIjoiQ2FuZHJhQGdtYWlsLmNvbSIsIk5hbWEiOiJDYW5kcmEgUHV0cmEgV2lqYWtzYW5hIiwiUm9sZSI6IkFkbWluIiwidGltZSI6MTU2OTI2MjAzMn0.yIkijVwvcDHXtgtTmmQ_l9tgypUwaxziTO-rlZvrjCw

{
    "nama":"KTP"
}

###

Get http://testing.stimiksepnop.ac.id/api/Persyaratan HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjgiLCJVc2VybmFtZSI6IkNhbmRyYSIsIkVtYWlsIjoiQ2FuZHJhQGdtYWlsLmNvbSIsIk5hbWEiOiJDYW5kcmEgUHV0cmEgV2lqYWtzYW5hIiwiUm9sZSI6IkFkbWluIiwidGltZSI6MTU2OTI2MjAzMn0.yIkijVwvcDHXtgtTmmQ_l9tgypUwaxziTO-rlZvrjCw

###




Delete http://testing.stimiksepnop.ac.id/api/Persyaratan/1 HTTP/1.1
content-type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjgiLCJVc2VybmFtZSI6IkNhbmRyYSIsIkVtYWlsIjoiQ2FuZHJhQGdtYWlsLmNvbSIsIk5hbWEiOiJDYW5kcmEgUHV0cmEgV2lqYWtzYW5hIiwiUm9sZSI6IkFkbWluIiwidGltZSI6MTU2OTI2MjAzMn0.yIkijVwvcDHXtgtTmmQ_l9tgypUwaxziTO-rlZvrjCw

###
